name: Deploy Void Linux packages

on:
  workflow_run:
    workflows: [Build Void Linux packages]
    branches: [main]
    types:
      - completed

env:
  XBPS_ARCH: x86_64
  XBPS_TARGET_ARCH: x86_64

jobs:
  deploy:
    name: Deploy all packages
    runs-on: ubuntu-latest
    needs:
      - init
      - build
    permissions:
      contents: write

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Install latest version of xbps
        run: |
          curl -L https://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz -o xbps.tar.xz
          tar -xJvf xbps.tar.xz
          rm xbps.tar.xz
          echo "$(pwd)/usr/bin" >> $GITHUB_PATH

      - name: Copy all packages into void directory
        run: |
          mkdir -p current
          cp ./artifacts/*/*.xbps ./current

      - name: Add all packages to the repository
        run: |
          cd current
          for pkg in *.xbps; do
            xbps-rindex --add $pkg
          done

      - name: Remove all packages that are no longer built
        env:
          PACKAGES: ${{ needs.init.outputs.packages }}
        run: |
          mv ./current ./previous
          mkdir ./current
          cp ./previous/${XBPS_ARCH}-repodata ./current/${XBPS_ARCH}-repodata
          for pkg in $(echo "$PACKAGES" | jq --raw-output '.package[]'); do
            pkgver=$(xbps-query --repository="$(pwd)/previous" --show $pkg --property pkgver)
            mv $(pwd)/previous/$pkgver.$XBPS_ARCH.xbps $(pwd)/current
          done

      - name: Sign all packages in the repository
        run: |
          echo "${{ secrets.VOID_REPO_SIGNING_KEY }}" > private.pem
          xbps-rindex \
            --privkey private.pem \
            --sign \
            --signedby "Jonatha Gabriel <jonathagabrielns@gmail.com>" \
            "$(pwd)/current"
          for pkg in ./current/*.xbps; do
            xbps-rindex --privkey private.pem --sign-pkg $pkg
          done

      - name: Clean up repositories
        run: |
          xbps-rindex --clean "$(pwd)/current"
          xbps-rindex --remove-obsoletes "$(pwd)/current"

      - name: Push updated repository to remote
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload Void Linux packages
          file_pattern: "current/*"
          push_options: "--force"

